### PR TITLE
site.title -> site.description fix

### PR DESCRIPTION
**Pull request by bebo-dot-dev**
site.title doesn't exist as a property in _config.yml. This fix enables the title to be set to the default site.description property value on pages that don't have a title property e.g. index.html

### CODE REVIEW

**Comment by willianjusten** [comment]
Hum... I prefer to put a site.title on _config.yml instead of use site.description... What do you think about it?

**Comment by bebo-dot-dev** [comment]
yes that would work too aka leave the markup as-is and introduce the prop to _config.yml

**Comment by willianjusten** [comment]
Yeah, can you put this property on config.yml for me please? To close this PR.

**Comment by bebo-dot-dev** [comment]
sure will do - I'll rewind time on this and do that now :)

**Comment by bebo-dot-dev** [comment]
that should do it thanks

**Comment by willianjusten** [comment]
Thanks =)

**Pull request merged**
